apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Elasticsearch"
  name: elasticsearch-logging
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: es-port
  selector:
    name: elasticsearch-logging
